name: Chained GET Requests

on:
  schedule:
    - cron: '15 18 * * *' # Adjust to your preferred UTC time (e.g., 2:30 AM IST)

jobs:
  post-task:
    runs-on: ubuntu-latest

    steps:
      # First GET request to /log_missing_meals
      - name: Get Missing Meals Log
        run: |
          echo "Making first GET request to /log_missing_meals"
          # Make the GET request and capture both the output and the HTTP status code
          response=$(curl -s -w "%{http_code}" -o response.json https://diet-be.onrender.com/log_missing_meals)
          http_code=$(echo "$response" | tail -n 1)  # Extract HTTP status code
          
          echo "Response status code: $http_code"
          # Check if the response status code is 200 (OK)
          if [ "$http_code" -eq 200 ]; then
            echo "First request successful, proceeding to second request"
          else
            echo "First request failed with status code $http_code"
            exit 1  # Exit if the first request fails
          fi
        
      # Second GET request to /ai_adjustment, triggered after the first one finishes successfully
      - name: Get AI Adjustment
        run: |
          echo "Making second GET request to /ai_adjustment"
          response=$(curl -s -w "%{http_code}" -o response.json https://diet-be.onrender.com/ai_adjustment)
          http_code=$(echo "$response" | tail -n 1)  # Extract HTTP status code
          
          echo "Response status code: $http_code"
          if [ "$http_code" -eq 200 ]; then
            echo "Second request successful"
          else
            echo "Second request failed with status code $http_code"
            exit 1  # Exit if the second request fails
          fi
